#!/bin/sh
############################################
# Copyright (C) 24/10/2020 - Brice GIBOUDEAU
#
# Libraries to manage system with OpenWisP
############################################
#
#
#Includes
. /etc/openwisp/openwisp-system-management.sh
#
#
#
REBOOT_FLAG=0
#
#
Do_I_Need_To_Reboot
#
#
#
exit 0
