#!/bin/sh
############################################
# Copyright (C) 24/10/2020 - Brice GIBOUDEAU
#
# Libraries to manage system with OpenWisP
############################################
#
#
#Includes
. /etc/openwisp/openwisp-system-management.sh
#
#
Backup_Upgrade_fct
#
Firmware_Upgrade_fct
#
Remove_Packages_fct
#
Install_Packages_fct
#
Execute_Tasks_fct
#
#
#
exit 0
